# Generated by Django 5.1.6 on 2025-02-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_remove_profile_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='pfp.png', upload_to='profile_pics'),
        ),
    ]
