# Generated by Django 5.1.6 on 2025-02-21 09:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_tournament_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='tournament_upvotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
