# Generated by Django 5.1.6 on 2025-02-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_tournament_upvotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='logo',
            field=models.ImageField(default='tournament.png', upload_to='tournament_logos'),
        ),
    ]
