# Generated by Django 5.1.6 on 2025-02-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_tournament_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='logo',
            field=models.ImageField(default='tournament.png', upload_to='tournament_logos/'),
        ),
    ]
