# Generated by Django 5.1.6 on 2025-02-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0007_alter_tournament_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentparticipant',
            name='ranking',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
