# Generated by Django 5.1.6 on 2025-02-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0008_tournamentparticipant_ranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_picture',
            field=models.ImageField(default='game.png', upload_to='game_pics'),
        ),
    ]
